### PR TITLE
Creation & development of the Entity & Restful of Dwelling and Message

### PR DESCRIPTION
**Pull request by Arruza17**
The development of the entities is done and ready to merge with the master

### CODE REVIEW

**Comment by Arruza17** [comment]
Probably some of the xml transient need to change but we will change it after the merge into the master

**Comment by jorgeccst** [comment]
On commentFacadeRest at Line 63 ```@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})```  MediaType.APPLICATION_JSON left, not grave but must be changed, ready to merge.

**Comment by AdrianPerez09** [comment]
Everything fine , ready to merge.

**Comment by Arruza17** [comment]
> On commentFacadeRest at Line 63 `@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})` MediaType.APPLICATION_JSON left, not grave but must be changed, ready to merge.

Yeah, after the pull I will change it

**Pull request merged**
