### PR TITLE
User Issues

### PR DESCRIPTION
**Pull request by yeraysampedro**
After spending long hours today, I achieved to solve all the issues. Not going to lie, I don't even know what I did to solve them rather than renewing the Private key. Anyways, it now connects correctly with the client

### CODE REVIEW

**Review by Arruza17 — APPROVED** [review]
When working with private key's is better to return them in a byte[] rather than in a String, the Restful looks fine for me

**Review by jorgeccst — APPROVED** [review]
Everything ok. ready to merge.

**Review by AdrianPerez09 — APPROVED** [review]
Everything ok. Ready to merge

**Comment by Arruza17** [comment]
Done

**Pull request merged**
