### PR TITLE
Dev Restful

### PR DESCRIPTION
**Pull request by yeraysampedro**
I finished correcting the problems with the generation of the RESTful. 

In order to be able to use it, you need to use a [custom script](https://drive.google.com/file/d/1vj4rRHn58ylmh_BF1i7s7B3iXJFi7Mks/view?usp=sharing) since the deployment generates the tables in a wrong order

### CODE REVIEW

**Comment by Arruza17** [comment]
Those Restful have given us headaches! Nice and clean code. I dont think that we need the web package with everything inside but its ok for me. Go ahead

**Comment by AdrianPerez09** [comment]
Everything is ok and it's ready for the merge with the master branch.

**Comment by jorgeccst** [comment]
Nice Javadoc!
Ready to merge with master branch, no errors spotted.

**Comment by Arruza17** [comment]
> Nice Javadoc! Ready to merge with master branch, no errors spotted.

No errors yet...

**Pull request merged**
