### PR TITLE
Dev q service facility neighborhood

### PR DESCRIPTION
**Pull request by AdrianPerez09**
Entity classes: Service, Facility, Neighbourhood

### CODE REVIEW

**Comment by jorgeccst** [comment]
Everything ok, ready to merge.

**Comment by yeraysampedro** [comment]
Everything alright! Just missing Ander's opinion

**Comment by Arruza17** [comment]
Which were the main problem while mergeing into master?

**Comment by Arruza17** [comment]
> Everything alright! Just missing Ander's opinion

Just checking everything you know :)

**Comment by AdrianPerez09** [comment]
> Which were the main problem while mergeing into master?

There were  conflicts with the  ```@author``` javadoc annotation in some classes.

**Pull request merged**
